import type { ApiEndpointDemo } from "./types";

/** Application API (machine key / admin provisioning). */
export const APPLICATION_DEMOS: ApiEndpointDemo[] = [
  {
    id: "app-users",
    group: "Application API",
    title: "List users",
    description: "Machine key: list all panel users (billing / provisioning).",
    method: "GET",
    path: "/api/application/users",
    auth: "gta",
    safe: true,
  },
  {
    id: "app-servers",
    group: "Application API",
    title: "List servers (all)",
    description: "Machine key: list every server on the panel.",
    method: "GET",
    path: "/api/application/servers",
    auth: "gta",
    safe: true,
  },
  {
    id: "app-create-server",
    group: "Application API",
    title: "Create server",
    description: "Provision a server for an owner after payment.",
    method: "POST",
    path: "/api/application/servers",
    auth: "gta",
    body: {
      ownerId: "USER_ID",
      name: "Survival",
      type: "PAPER",
      mcVersion: "1.21.1",
      port: 25565,
      memoryMb: 4096,
      diskMb: 10240,
    },
    safe: false,
  },
  {
    id: "app-power",
    group: "Application API",
    title: "Power (admin)",
    description: "Start/stop any server with servers.power scope.",
    method: "POST",
    path: "/api/application/servers/{serverId}/power",
    auth: "gta",
    body: { signal: "stop" },
    safe: false,
  },
  {
    id: "app-suspend",
    group: "Application API",
    title: "Suspend server",
    description: "Billing suspend — stops the server and blocks start until cleared.",
    method: "PATCH",
    path: "/api/application/servers/{serverId}",
    auth: "gta",
    body: { suspended: true },
    safe: false,
  },
  {
    id: "app-connect",
    group: "Application API",
    title: "Connect info (admin)",
    description: "Join address + SFTP meta for any server (servers.read).",
    method: "GET",
    path: "/api/application/servers/{serverId}/connect",
    auth: "gta",
    safe: true,
  },
  {
    id: "app-files",
    group: "Application API",
    title: "List files (admin)",
    description: "File listing via servers.files scope.",
    method: "GET",
    path: "/api/application/servers/{serverId}/files",
    query: "path=.",
    auth: "gta",
    safe: true,
  },
  {
    id: "app-addons",
    group: "Application API",
    title: "List addons (admin)",
    description: "Installed mods/plugins via servers.addons.",
    method: "GET",
    path: "/api/application/servers/{serverId}/addons",
    auth: "gta",
    safe: true,
  },
  {
    id: "app-backups",
    group: "Application API",
    title: "List backups (admin)",
    description: "Backup inventory via servers.backups.",
    method: "GET",
    path: "/api/application/servers/{serverId}/backups",
    auth: "gta",
    safe: true,
  },
  {
    id: "app-allocations",
    group: "Application API",
    title: "List allocations (admin)",
    description: "Network ports via servers.allocations.",
    method: "GET",
    path: "/api/application/servers/{serverId}/allocations",
    auth: "gta",
    safe: true,
  },
  {
    id: "app-databases",
    group: "Application API",
    title: "List databases (admin)",
    description: "MySQL databases via servers.databases.",
    method: "GET",
    path: "/api/application/servers/{serverId}/databases",
    auth: "gta",
    safe: true,
  },
];
