import type { ApiEndpointDemo } from "./types";
import { SAMPLE_STORAGE_GET, SAMPLE_STORAGES_LIST } from "./samples";

/** Application API (machine key / admin provisioning). */
export const APPLICATION_DEMOS: ApiEndpointDemo[] = [
  {
    id: "app-users",
    group: "Application API",
    title: "List users",
    description: "Machine key: list all panel users (billing / provisioning).",
    method: "GET",
    path: "/api/application/users",
    auth: "gta",
    safe: true,
  },
  {
    id: "app-servers",
    group: "Application API",
    title: "List servers (all)",
    description: "Machine key: list every server on the panel.",
    method: "GET",
    path: "/api/application/servers",
    auth: "gta",
    safe: true,
  },
  {
    id: "app-nodes",
    group: "Application API",
    title: "List nodes",
    description: "Deployable nodes with usage (nodes.read).",
    method: "GET",
    path: "/api/application/nodes",
    auth: "gta",
    safe: true,
  },
  {
    id: "app-storages",
    group: "Application API",
    title: "List storage pools",
    description: "Global local/NFS pools and node links (nodes.read). Use id as storageId on create.",
    method: "GET",
    path: "/api/application/storages",
    auth: "gta",
    safe: true,
    sampleResponse: SAMPLE_STORAGES_LIST,
  },
  {
    id: "app-storage-get",
    group: "Application API",
    title: "Get storage pool",
    description: "Single pool by id — links, mount status, disk usage (nodes.read).",
    method: "GET",
    path: "/api/application/storages/{storageId}",
    auth: "gta",
    safe: true,
    sampleResponse: SAMPLE_STORAGE_GET,
  },
  {
    id: "app-node-storages",
    group: "Application API",
    title: "List storages for node",
    description: "Pools linked to a node — pick storageId for POST /api/application/servers.",
    method: "GET",
    path: "/api/application/nodes/{nodeId}/storages",
    auth: "gta",
    safe: true,
    sampleResponse: SAMPLE_STORAGES_LIST,
  },
  {
    id: "app-create-server",
    group: "Application API",
    title: "Create server",
    description:
      "Provision a server for an owner after payment. Omit nodeId/storageId for auto placement (RAM → CPU → disk). List pools: GET /api/application/storages or GET /api/application/nodes/:id/storages.",
    method: "POST",
    path: "/api/application/servers",
    auth: "gta",
    body: {
      ownerId: "USER_ID",
      name: "Survival",
      type: "PAPER",
      mcVersion: "1.21.1",
      port: 25565,
      memoryMb: 4096,
      diskMb: 10240,
    },
    bodyFields: [
      { name: "ownerId", required: true, description: "Panel user id (owner of the server)" },
      { name: "name", required: true, description: "Server display name" },
      { name: "type", required: true, description: "PAPER, PURPUR, VANILLA, FABRIC, …" },
      { name: "mcVersion", required: true, description: "Minecraft version string" },
      { name: "port", required: true, description: "Primary game port (1024–65535)" },
      { name: "memoryMb", required: true, description: "RAM limit in MB" },
      { name: "diskMb", description: "Disk quota in MB (default from panel)" },
      { name: "cpuLimit", description: "CPU limit (0–6400)" },
      {
        name: "nodeId",
        description:
          "Manual override — force this node. Omit for automatic placement (most free RAM → CPU on deployable ONLINE nodes).",
      },
      {
        name: "storageId",
        description:
          "Storage pool id from GET /api/application/storages. Omit = auto on node; null = node DATA_DIR only.",
      },
      { name: "paperBuild", description: "PAPER/PURPUR build id; omit for latest/STABLE" },
      { name: "fabricLoaderVersion", description: "FABRIC/QUILT loader; omit for stable/latest" },
      { name: "forgeVersion", description: "FORGE/NEOFORGE version; omit for recommended/latest" },
    ],
    safe: false,
  },
  {
    id: "app-power",
    group: "Application API",
    title: "Power (admin)",
    description: "Start/stop any server with servers.power scope.",
    method: "POST",
    path: "/api/application/servers/{serverId}/power",
    auth: "gta",
    body: { signal: "stop" },
    safe: false,
  },
  {
    id: "app-suspend",
    group: "Application API",
    title: "Suspend server",
    description: "Billing suspend — stops the server and blocks start until cleared.",
    method: "PATCH",
    path: "/api/application/servers/{serverId}",
    auth: "gta",
    body: { suspended: true },
    safe: false,
  },
  {
    id: "app-connect",
    group: "Application API",
    title: "Connect info (admin)",
    description: "Join address + SFTP meta for any server (servers.read).",
    method: "GET",
    path: "/api/application/servers/{serverId}/connect",
    auth: "gta",
    safe: true,
  },
  {
    id: "app-files",
    group: "Application API",
    title: "List files (admin)",
    description: "File listing via servers.files scope.",
    method: "GET",
    path: "/api/application/servers/{serverId}/files",
    query: "path=.",
    auth: "gta",
    safe: true,
  },
  {
    id: "app-addons",
    group: "Application API",
    title: "List addons (admin)",
    description: "Installed mods/plugins via servers.addons.",
    method: "GET",
    path: "/api/application/servers/{serverId}/addons",
    auth: "gta",
    safe: true,
  },
  {
    id: "app-backups",
    group: "Application API",
    title: "List backups (admin)",
    description: "Backup inventory via servers.backups.",
    method: "GET",
    path: "/api/application/servers/{serverId}/backups",
    auth: "gta",
    safe: true,
  },
  {
    id: "app-allocations",
    group: "Application API",
    title: "List allocations (admin)",
    description: "Network ports via servers.allocations.",
    method: "GET",
    path: "/api/application/servers/{serverId}/allocations",
    auth: "gta",
    safe: true,
  },
  {
    id: "app-databases",
    group: "Application API",
    title: "List databases (admin)",
    description: "MySQL databases via servers.databases.",
    method: "GET",
    path: "/api/application/servers/{serverId}/databases",
    auth: "gta",
    safe: true,
  },
];
