import type { ApiEndpointDemo } from "./types";

/** Client API — per-server endpoints. */
export const SERVERS_DEMOS: ApiEndpointDemo[] = [
  {
    id: "servers-list",
    group: "Client API",
    title: "List servers",
    description: "All servers visible to this key (JSON array).",
    method: "GET",
    path: "/api/servers",
    auth: "gt",
    safe: true,
  },
  {
    id: "server-get",
    group: "Client API",
    title: "Get server",
    description: "Single server details including status and permissions.",
    method: "GET",
    path: "/api/servers/{serverId}",
    auth: "gt",
    safe: true,
  },
  {
    id: "server-stats",
    group: "Client API",
    title: "Live stats",
    description: "CPU / RAM / network (and optional disk) for one server.",
    method: "GET",
    path: "/api/servers/{serverId}/stats",
    query: "disk=1",
    auth: "gt",
    safe: true,
  },
  {
    id: "server-start",
    group: "Client API",
    title: "Start server",
    description: "Start the Minecraft process. Needs permission control.start. Body: none.",
    method: "POST",
    path: "/api/servers/{serverId}/start",
    auth: "gt",
    safe: false,
    sampleResponse: {
      id: "V1StGXR8_Z5j",
      name: "Survival SMP",
      status: "STARTING",
    },
  },
  {
    id: "server-stop",
    group: "Client API",
    title: "Stop server",
    description: "Graceful stop (sends stop to the process). Needs permission control.stop.",
    method: "POST",
    path: "/api/servers/{serverId}/stop",
    auth: "gt",
    safe: false,
    sampleResponse: {
      id: "V1StGXR8_Z5j",
      status: "STOPPING",
    },
  },
  {
    id: "server-restart",
    group: "Client API",
    title: "Restart server",
    description: "Stop then start. Needs permission control.restart.",
    method: "POST",
    path: "/api/servers/{serverId}/restart",
    auth: "gt",
    safe: false,
    sampleResponse: {
      id: "V1StGXR8_Z5j",
      status: "STARTING",
    },
  },
  {
    id: "server-kill",
    group: "Client API",
    title: "Kill server",
    description:
      "Force-kill the container/process (no graceful save). Needs permission control.kill.",
    method: "POST",
    path: "/api/servers/{serverId}/kill",
    auth: "gt",
    safe: false,
    sampleResponse: {
      id: "V1StGXR8_Z5j",
      status: "STOPPED",
    },
  },
  {
    id: "server-power",
    group: "Client API",
    title: "Power (unified)",
    description: "Unified power endpoint. Body signal: start | stop | restart | kill.",
    method: "POST",
    path: "/api/servers/{serverId}/power",
    auth: "gt",
    body: { signal: "start" },
    safe: false,
  },
  {
    id: "server-command",
    group: "Client API",
    title: "Send console command",
    description:
      "One-shot console command over HTTP. Waits briefly and returns captured console lines in the response.",
    method: "POST",
    path: "/api/servers/{serverId}/command",
    auth: "gt",
    body: { command: "list" },
    safe: false,
    sampleResponse: {
      ok: true,
      command: "list",
      lines: ["There are 2 of a max of 20 players online: Steve, Alex"],
      output: "There are 2 of a max of 20 players online: Steve, Alex",
      timedOut: false,
    },
  },
  {
    id: "server-websocket",
    group: "Client API",
    title: "WebSocket info",
    description: "Returns console / players WebSocket URLs for API clients.",
    method: "GET",
    path: "/api/servers/{serverId}/websocket",
    auth: "gt",
    safe: true,
  },
  {
    id: "server-files",
    group: "Client API",
    title: "List files",
    description: "Directory listing for the server file manager.",
    method: "GET",
    path: "/api/servers/{serverId}/files",
    query: "path=.",
    auth: "gt",
    safe: true,
  },
  {
    id: "server-files-content",
    group: "Client API",
    title: "Read file content",
    description: "Read a text file from the server data directory.",
    method: "GET",
    path: "/api/servers/{serverId}/files/content",
    query: "path=server.properties",
    auth: "gt",
    safe: true,
  },
  {
    id: "server-patch",
    group: "Client API",
    title: "Update server settings",
    description: "Patch name, server.properties, startup, or limits (permission-gated).",
    method: "PATCH",
    path: "/api/servers/{serverId}",
    auth: "gt",
    body: {
      name: "Survival",
      properties: { motd: "Welcome!", "max-players": "40" },
    },
    safe: false,
  },
  {
    id: "server-addons",
    group: "Client API",
    title: "List installed addons",
    description: "Installed mods/plugins with Modrinth metadata when available.",
    method: "GET",
    path: "/api/servers/{serverId}/addons",
    auth: "gt",
    safe: true,
  },
  {
    id: "server-addons-install",
    group: "Client API",
    title: "Install addon",
    description: "Install a Modrinth project onto the server (addon.update).",
    method: "POST",
    path: "/api/servers/{serverId}/addons/install",
    auth: "gt",
    body: { projectId: "fabric-api" },
    safe: false,
  },
  {
    id: "server-addons-delete",
    group: "Client API",
    title: "Remove addon",
    description: "Uninstall an addon by Modrinth project id.",
    method: "DELETE",
    path: "/api/servers/{serverId}/addons/{projectId}",
    auth: "gt",
    safe: false,
  },
  {
    id: "server-backups",
    group: "Client API",
    title: "List backups",
    description: "Backup inventory for a server.",
    method: "GET",
    path: "/api/servers/{serverId}/backups",
    auth: "gt",
    safe: true,
  },
  {
    id: "server-backups-create",
    group: "Client API",
    title: "Create backup",
    description: "Start a new backup (backup.create).",
    method: "POST",
    path: "/api/servers/{serverId}/backups",
    auth: "gt",
    body: { note: "Pre-update snapshot" },
    safe: false,
  },
  {
    id: "server-allocations",
    group: "Client API",
    title: "List allocations",
    description: "Network ports assigned to this server.",
    method: "GET",
    path: "/api/servers/{serverId}/allocations",
    auth: "gt",
    safe: true,
  },
  {
    id: "server-connect",
    group: "Client API",
    title: "Connect info (game + SFTP)",
    description:
      "Join address, MOTD, and SFTP host/port/username when file.sftp is allowed. Password is an app password (gtap_), not returned here.",
    method: "GET",
    path: "/api/servers/{serverId}/connect",
    auth: "gt",
    safe: true,
    sampleResponse: {
      host: "play.example.com",
      port: 25565,
      address: "play.example.com",
      sftpEnabled: true,
      sftpHost: "node1.example.com",
      sftpPort: 2022,
      sftpUsername: "steve.V1StGXR8_Z5j",
    },
  },
  {
    id: "server-databases",
    group: "Client API",
    title: "List databases",
    description: "MySQL databases for this server (includes password).",
    method: "GET",
    path: "/api/servers/{serverId}/databases",
    auth: "gt",
    safe: true,
  },
  {
    id: "server-db-rotate",
    group: "Client API",
    title: "Rotate database password",
    description: "Generate a new MySQL password (database.update).",
    method: "POST",
    path: "/api/servers/{serverId}/databases/{dbId}/rotate-password",
    auth: "gt",
    safe: false,
  },
];
