import type { WikiArticle } from "../wiki-types";

export const operationsArticles: WikiArticle[] = [
  {
    slug: "statusline",
    title: "Status overview",
    summary: "Admin → Status health board for web, API, watchdog, Redis, and every game node.",
    category: "Operations",
    keywords: ["status", "statusline", "health", "watchdog", "nodes"],
    sourcePath: "docs/wiki/statusline.md",
    relatedSlugs: ["operations", "install-nodes", "scaling"],
    sections: [],
  },
  {
    slug: "security",
    title: "Security",
    summary:
      "Review the main hardening controls for sessions, proxy trust, daemon auth, SFTP jail, secrets, and host exposure.",
    category: "Operations",
    keywords: ["security", "sessions", "csrf", "daemon jwt", "sftp", "rotation", "cloudflare"],
    sourcePath: "docs/wiki/security.md",
    relatedSlugs: ["accounts-quotas", "daemon-api", "license-flow"],
    sections: [],
  },
  {
    slug: "licensing",
    title: "Licensing",
    summary:
      "Connect the panel to the public license API, understand free-tier fallback, and see how the daemon enforces signed ticket limits.",
    category: "Operations",
    keywords: ["license", "free tier", "validate", "ticket", "limits", "features"],
    sourcePath: "docs/wiki/licensing.md",
    relatedSlugs: ["license-flow", "security", "install-panel"],
    sections: [],
  },
  {
    slug: "panel-settings",
    title: "Panel settings",
    summary:
      "Configure public URLs, registration, SMTP, security flags, Redis visibility, alerts, and the Go-live readiness tab from Admin -> Settings.",
    category: "Operations",
    keywords: [
      "settings",
      "smtp",
      "registration",
      "redis",
      "alerts",
      "public host",
      "go-live",
      "sla",
    ],
    sourcePath: "docs/wiki/panel-settings.md",
    relatedSlugs: ["sla-ops", "security", "operations", "notifications-alerts"],
    sections: [],
  },
  {
    slug: "sla-ops",
    title: "SLA ops",
    summary:
      "Templates for managed SaaS posture: HA env, incident steps, restore/secret drills, monitoring, and pentest process.",
    category: "Operations",
    keywords: [
      "sla",
      "go-live",
      "bullmq",
      "require_redis_ha",
      "restore drill",
      "pentest",
      "rto",
      "rpo",
    ],
    sourcePath: "docs/wiki/sla-ops.md",
    relatedSlugs: ["panel-settings", "scaling", "security", "upgrade-to-1.2"],
    sections: [],
  },
  {
    slug: "activity-log",
    title: "Activity log",
    summary:
      "Track power actions, settings changes, files, backups, subusers, auth events, and node/system activity across the platform.",
    category: "Operations",
    keywords: ["activity", "audit", "events", "filters", "alerts", "retention"],
    sourcePath: "docs/wiki/activity-log.md",
    relatedSlugs: ["notifications-alerts", "security", "server-management"],
    sections: [],
  },
  {
    slug: "scaling",
    title: "Scaling and Redis",
    summary:
      "Understand the supported scale model, when Redis is needed, and how sessions, rate limits, transfers, and event fan-out behave.",
    category: "Operations",
    keywords: ["scaling", "redis", "multi-api", "ha", "sessions", "rate limits"],
    sourcePath: "docs/wiki/scaling.md",
    relatedSlugs: ["install-panel", "security", "operations"],
    sections: [],
  },
  {
    slug: "upgrade-to-1.1",
    title: "Upgrade to 1.1",
    summary:
      "Upgrade an existing 1.0.x panel to Guartrix 1.1.0: env knobs, migrate, rebuild, and scale smoke.",
    category: "Operations",
    keywords: ["upgrade", "1.1", "migrate", "scale", "redis", "rate limit"],
    sourcePath: "docs/wiki/upgrade-to-1.1.md",
    relatedSlugs: ["upgrade-to-1.2", "scaling", "operations", "env-reference"],
    sections: [],
  },
  {
    slug: "upgrade-to-1.2",
    title: "Upgrade to 1.2",
    summary:
      "Upgrade 1.1.x to 1.2 SaaS/SLA: Go-live, BullMQ, /api/v1, peer-only transfers, HA flag.",
    category: "Operations",
    keywords: ["upgrade", "1.2", "saas", "sla", "bullmq", "api/v1", "go-live", "transfer"],
    sourcePath: "docs/wiki/upgrade-to-1.2.md",
    relatedSlugs: ["sla-ops", "upgrade-to-1.1", "scaling", "panel-settings"],
    sections: [],
  },
  {
    slug: "operations",
    title: "Operations",
    summary:
      "Operate the production stack with the start script, watchdog, backups, ports, and public install endpoints.",
    category: "Operations",
    keywords: ["operations", "start", "watchdog", "backup", "ports", "health", "prod-web"],
    sourcePath: "docs/wiki/operations.md",
    relatedSlugs: ["install-panel", "security", "daemon-api"],
    sections: [],
  },
];
