/** Auto-generated from apps/api/src/mail-templates/* — run: node scripts/generate-mail-templates.mjs */

export const MAIL_TEMPLATE_FILES: Record<string, string> = {
  "alert.html": "<p style=\"margin:0 0 16px;font-size:16px;line-height:1.5;font-weight:600;\">{{eventTitle}}</p>\n<pre style=\"margin:0;padding:16px;background:#f8fafc;border:1px solid #e2e8f0;border-radius:6px;font-size:13px;line-height:1.5;white-space:pre-wrap;word-break:break-word;font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace;color:#334155;\">{{eventBody}}</pre>\n",
  "alert.subject.txt": "[{{appName}}] {{eventTitle}}\n",
  "alert.txt": "{{eventTitle}}\n\n{{eventBody}}\n",
  "invite-server.html": "<p style=\"margin:0 0 16px;font-size:16px;line-height:1.5;\">Hi{{#username}} {{username}}{{/username}},</p>\n<p style=\"margin:0 0 16px;font-size:15px;line-height:1.6;color:#334155;\"><strong>{{inviterName}}</strong> invited you to manage <strong>{{serverName}}</strong> on {{appName}}.</p>\n<p style=\"margin:0 0 24px;\">\n  <a href=\"{{actionUrl}}\" style=\"display:inline-block;background:#2563eb;color:#ffffff;text-decoration:none;font-weight:600;font-size:14px;padding:12px 20px;border-radius:6px;\">Accept invite</a>\n</p>\n<p style=\"margin:0 0 8px;font-size:13px;line-height:1.5;color:#64748b;\">Or open this link (sign in with this email):</p>\n<p style=\"margin:0 0 16px;font-size:13px;line-height:1.5;word-break:break-all;\"><a href=\"{{actionUrl}}\" style=\"color:#2563eb;\">{{actionUrl}}</a></p>\n<p style=\"margin:0;font-size:13px;color:#64748b;\">This link expires in {{expiresIn}}.</p>\n",
  "invite-server.subject.txt": "You've been invited to {{serverName}} on {{appName}}\n",
  "invite-server.txt": "Hi{{#username}} {{username}}{{/username}},\n\n{{inviterName}} invited you to manage \"{{serverName}}\" on {{appName}}.\nAccept the invite (sign in with this email):\n\n{{actionUrl}}\n\nThis link expires in {{expiresIn}}.\n",
  "invite-set-password.html": "<p style=\"margin:0 0 16px;font-size:16px;line-height:1.5;\">Hi {{username}},</p>\n<p style=\"margin:0 0 16px;font-size:15px;line-height:1.6;color:#334155;\"><strong>{{inviterName}}</strong> invited you to a Minecraft server on {{appName}}. A panel account was created for you — set your password to continue.</p>\n<p style=\"margin:0 0 24px;\">\n  <a href=\"{{actionUrl}}\" style=\"display:inline-block;background:#2563eb;color:#ffffff;text-decoration:none;font-weight:600;font-size:14px;padding:12px 20px;border-radius:6px;\">Set password</a>\n</p>\n<p style=\"margin:0 0 8px;font-size:13px;line-height:1.5;color:#64748b;\">Or open this link:</p>\n<p style=\"margin:0 0 16px;font-size:13px;line-height:1.5;word-break:break-all;\"><a href=\"{{actionUrl}}\" style=\"color:#2563eb;\">{{actionUrl}}</a></p>\n<p style=\"margin:0;font-size:13px;color:#64748b;\">This link expires in {{expiresIn}}. If you did not expect this invite, you can ignore this email.</p>\n",
  "invite-set-password.subject.txt": "You've been invited to {{appName}} — set your password\n",
  "invite-set-password.txt": "Hi {{username}},\n\n{{inviterName}} invited you to a Minecraft server on {{appName}}.\nA panel account was created for you. Set your password within {{expiresIn}}:\n\n{{actionUrl}}\n\nIf you did not expect this invite, you can ignore this email.\n",
  "layout.html": "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\" />\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n  <title>{{appName}}</title>\n</head>\n<body style=\"margin:0;padding:0;background:#f4f6f8;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;color:#1a1d21;\">\n  <table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" style=\"background:#f4f6f8;padding:32px 12px;\">\n    <tr>\n      <td align=\"center\">\n        <table role=\"presentation\" width=\"560\" cellspacing=\"0\" cellpadding=\"0\" style=\"max-width:560px;width:100%;background:#ffffff;border-radius:8px;overflow:hidden;border:1px solid #e5e9ef;\">\n          <tr>\n            <td style=\"padding:24px 28px 16px;border-bottom:1px solid #eef1f5;\">\n              {{#logo}}\n              <img src=\"{{logoUrl}}\" alt=\"{{appName}}\" height=\"36\" style=\"display:block;height:36px;width:auto;border:0;\" />\n              {{/logo}}\n              {{^logo}}\n              <div style=\"font-size:20px;font-weight:700;letter-spacing:-0.02em;color:#0f172a;\">{{appName}}</div>\n              {{/logo}}\n            </td>\n          </tr>\n          <tr>\n            <td style=\"padding:28px;\">\n              {{content}}\n            </td>\n          </tr>\n          <tr>\n            <td style=\"padding:16px 28px 24px;border-top:1px solid #eef1f5;font-size:12px;line-height:1.5;color:#6b7280;\">\n              Sent by {{appName}} · <a href=\"{{panelUrl}}\" style=\"color:#2563eb;text-decoration:none;\">{{panelUrl}}</a><br />\n              From {{fromAddress}}\n            </td>\n          </tr>\n        </table>\n      </td>\n    </tr>\n  </table>\n</body>\n</html>\n",
  "layout.txt": "{{appName}}\n{{panelUrl}}\n\n{{content}}\n\n--\nSent by {{appName}}\n{{panelUrl}}\nFrom {{fromAddress}}\n",
  "password-reset.html": "<p style=\"margin:0 0 16px;font-size:16px;line-height:1.5;\">Hi {{username}},</p>\n<p style=\"margin:0 0 16px;font-size:15px;line-height:1.6;color:#334155;\">We received a request to reset your {{appName}} panel password.</p>\n<p style=\"margin:0 0 24px;\">\n  <a href=\"{{actionUrl}}\" style=\"display:inline-block;background:#2563eb;color:#ffffff;text-decoration:none;font-weight:600;font-size:14px;padding:12px 20px;border-radius:6px;\">Reset password</a>\n</p>\n<p style=\"margin:0 0 8px;font-size:13px;line-height:1.5;color:#64748b;\">Or open this link:</p>\n<p style=\"margin:0 0 16px;font-size:13px;line-height:1.5;word-break:break-all;\"><a href=\"{{actionUrl}}\" style=\"color:#2563eb;\">{{actionUrl}}</a></p>\n<p style=\"margin:0;font-size:13px;color:#64748b;\">This link expires in {{expiresIn}}. If you did not request this, you can ignore this email.</p>\n",
  "password-reset.subject.txt": "Reset your {{appName}} password\n",
  "password-reset.txt": "Hi {{username}},\n\nWe received a request to reset your {{appName}} panel password.\nOpen this link within {{expiresIn}}:\n\n{{actionUrl}}\n\nIf you did not request this, you can ignore this email.\n",
  "test-mail.html": "<p style=\"margin:0 0 16px;font-size:16px;line-height:1.5;\">Hello,</p>\n<p style=\"margin:0 0 16px;font-size:15px;line-height:1.6;color:#334155;\">This is a test message from your {{appName}} panel. If you received this, outbound SMTP is working with the branded mail template.</p>\n<p style=\"margin:0 0 8px;font-size:13px;color:#64748b;\">Sent at {{sentAt}}</p>\n<p style=\"margin:0;font-size:13px;color:#64748b;\">SMTP: {{smtpHost}}:{{smtpPort}}</p>\n",
  "test-mail.subject.txt": "{{appName}} test mail\n",
  "test-mail.txt": "Hello,\n\nThis is a test message from your {{appName}} panel.\nIf you received this, outbound SMTP is working with the branded mail template.\n\nSent at {{sentAt}}\nSMTP: {{smtpHost}}:{{smtpPort}}\n",
  "verify-email.html": "<p style=\"margin:0 0 16px;font-size:16px;line-height:1.5;\">Hi {{username}},</p>\n<p style=\"margin:0 0 16px;font-size:15px;line-height:1.6;color:#334155;\">Confirm your email to finish setting up your {{appName}} account.</p>\n<p style=\"margin:0 0 24px;\">\n  <a href=\"{{actionUrl}}\" style=\"display:inline-block;background:#2563eb;color:#ffffff;text-decoration:none;font-weight:600;font-size:14px;padding:12px 20px;border-radius:6px;\">Verify email</a>\n</p>\n<p style=\"margin:0 0 8px;font-size:13px;line-height:1.5;color:#64748b;\">Or open this link:</p>\n<p style=\"margin:0 0 16px;font-size:13px;line-height:1.5;word-break:break-all;\"><a href=\"{{actionUrl}}\" style=\"color:#2563eb;\">{{actionUrl}}</a></p>\n<p style=\"margin:0;font-size:13px;color:#64748b;\">This link expires in {{expiresIn}}.</p>\n",
  "verify-email.subject.txt": "Verify your {{appName}} email\n",
  "verify-email.txt": "Hi {{username}},\n\nConfirm your email to finish setting up your {{appName}} account:\n\n{{actionUrl}}\n\nThis link expires in {{expiresIn}}.\n",
};
