/** Auto-generated from apps/api/src/mail-templates/* — run: node scripts/generate-mail-templates.mjs */

export const MAIL_TEMPLATE_FILES: Record<string, string> = {
  "alert.html": "<p style=\"margin:0 0 14px;font-size:16px;line-height:1.45;font-weight:600;color:#111827;\">{{eventTitle}}</p>\n<pre style=\"margin:0;padding:12px;background:#f8fafc;border:1px solid #d7dde5;font-size:13px;line-height:1.5;white-space:pre-wrap;word-break:break-word;font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace;color:#374151;\">{{eventBody}}</pre>\n",
  "alert.subject.txt": "[{{appName}}] {{eventTitle}}\n",
  "alert.txt": "{{eventTitle}}\n\n{{eventBody}}\n",
  "invite-server.html": "<p style=\"margin:0 0 14px;font-size:16px;line-height:1.45;color:#111827;\">Hi{{#username}} {{username}}{{/username}},</p>\n<p style=\"margin:0 0 18px;font-size:15px;line-height:1.55;color:#374151;\"><strong>{{inviterName}}</strong> invited you to manage <strong>{{serverName}}</strong> on {{appName}}.</p>\n<p style=\"margin:0 0 18px;\">\n  <a href=\"{{actionUrl}}\" style=\"display:inline-block;background:#2563eb;color:#ffffff;text-decoration:none;font-weight:600;font-size:14px;padding:11px 18px;border:1px solid #1d4ed8;\">Accept invite</a>\n</p>\n<p style=\"margin:0 0 6px;font-size:12px;line-height:1.45;color:#6b7280;\">Or open this link (sign in with this email):</p>\n<p style=\"margin:0 0 14px;font-size:13px;line-height:1.45;word-break:break-all;\"><a href=\"{{actionUrl}}\" style=\"color:#2563eb;\">{{actionUrl}}</a></p>\n<p style=\"margin:0;padding-top:12px;border-top:1px solid #d7dde5;font-size:12px;color:#6b7280;\">This link expires in {{expiresIn}}.</p>\n",
  "invite-server.subject.txt": "You've been invited to {{serverName}} on {{appName}}\n",
  "invite-server.txt": "Hi{{#username}} {{username}}{{/username}},\n\n{{inviterName}} invited you to manage \"{{serverName}}\" on {{appName}}.\nAccept the invite (sign in with this email):\n\n{{actionUrl}}\n\nThis link expires in {{expiresIn}}.\n",
  "invite-set-password.html": "<p style=\"margin:0 0 14px;font-size:16px;line-height:1.45;color:#111827;\">Hi {{username}},</p>\n<p style=\"margin:0 0 18px;font-size:15px;line-height:1.55;color:#374151;\"><strong>{{inviterName}}</strong> invited you to a Minecraft server on {{appName}}. A panel account was created for you — set your password to continue.</p>\n<p style=\"margin:0 0 18px;\">\n  <a href=\"{{actionUrl}}\" style=\"display:inline-block;background:#2563eb;color:#ffffff;text-decoration:none;font-weight:600;font-size:14px;padding:11px 18px;border:1px solid #1d4ed8;\">Set password</a>\n</p>\n<p style=\"margin:0 0 6px;font-size:12px;line-height:1.45;color:#6b7280;\">Or open this link:</p>\n<p style=\"margin:0 0 14px;font-size:13px;line-height:1.45;word-break:break-all;\"><a href=\"{{actionUrl}}\" style=\"color:#2563eb;\">{{actionUrl}}</a></p>\n<p style=\"margin:0;padding-top:12px;border-top:1px solid #d7dde5;font-size:12px;color:#6b7280;\">This link expires in {{expiresIn}}. If you did not expect this invite, you can ignore this email.</p>\n",
  "invite-set-password.subject.txt": "You've been invited to {{appName}} — set your password\n",
  "invite-set-password.txt": "Hi {{username}},\n\n{{inviterName}} invited you to a Minecraft server on {{appName}}.\nA panel account was created for you. Set your password within {{expiresIn}}:\n\n{{actionUrl}}\n\nIf you did not expect this invite, you can ignore this email.\n",
  "layout.html": "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\" />\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n  <title>{{appName}}</title>\n</head>\n<body style=\"margin:0;padding:0;background:#eef1f4;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;color:#111827;\">\n  <table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" style=\"background:#eef1f4;padding:28px 12px;\">\n    <tr>\n      <td align=\"center\">\n        <table role=\"presentation\" width=\"560\" cellspacing=\"0\" cellpadding=\"0\" style=\"max-width:560px;width:100%;background:#ffffff;border:1px solid #d7dde5;\">\n          <tr>\n            <td style=\"padding:18px 24px;border-bottom:1px solid #d7dde5;\">\n              {{#logo}}\n              <img src=\"{{logoUrl}}\" alt=\"{{appName}}\" height=\"32\" style=\"display:block;height:32px;width:auto;border:0;\" />\n              {{/logo}}\n              {{^logo}}\n              <div style=\"font-size:18px;font-weight:700;letter-spacing:-0.01em;color:#111827;\">{{appName}}</div>\n              {{/logo}}\n            </td>\n          </tr>\n          <tr>\n            <td style=\"padding:24px;\">\n              {{content}}\n            </td>\n          </tr>\n          <tr>\n            <td style=\"padding:14px 24px;border-top:1px solid #d7dde5;font-size:12px;line-height:1.5;color:#6b7280;\">\n              Sent by {{appName}} · <a href=\"{{panelUrl}}\" style=\"color:#2563eb;text-decoration:none;\">{{panelUrl}}</a><br />\n              From {{fromAddress}}\n            </td>\n          </tr>\n        </table>\n      </td>\n    </tr>\n  </table>\n</body>\n</html>\n",
  "layout.txt": "{{appName}}\n{{panelUrl}}\n\n{{content}}\n\n--\nSent by {{appName}}\n{{panelUrl}}\nFrom {{fromAddress}}\n",
  "password-reset.html": "<p style=\"margin:0 0 14px;font-size:16px;line-height:1.45;color:#111827;\">Hi {{username}},</p>\n<p style=\"margin:0 0 18px;font-size:15px;line-height:1.55;color:#374151;\">We received a request to reset your {{appName}} panel password.</p>\n<p style=\"margin:0 0 18px;\">\n  <a href=\"{{actionUrl}}\" style=\"display:inline-block;background:#2563eb;color:#ffffff;text-decoration:none;font-weight:600;font-size:14px;padding:11px 18px;border:1px solid #1d4ed8;\">Reset password</a>\n</p>\n<p style=\"margin:0 0 6px;font-size:12px;line-height:1.45;color:#6b7280;\">Or open this link:</p>\n<p style=\"margin:0 0 14px;font-size:13px;line-height:1.45;word-break:break-all;\"><a href=\"{{actionUrl}}\" style=\"color:#2563eb;\">{{actionUrl}}</a></p>\n<p style=\"margin:0;padding-top:12px;border-top:1px solid #d7dde5;font-size:12px;color:#6b7280;\">This link expires in {{expiresIn}}. If you did not request this, you can ignore this email.</p>\n",
  "password-reset.subject.txt": "Reset your {{appName}} password\n",
  "password-reset.txt": "Hi {{username}},\n\nWe received a request to reset your {{appName}} panel password.\nOpen this link within {{expiresIn}}:\n\n{{actionUrl}}\n\nIf you did not request this, you can ignore this email.\n",
  "test-mail.html": "<p style=\"margin:0 0 14px;font-size:16px;line-height:1.45;color:#111827;\">Hello,</p>\n<p style=\"margin:0 0 18px;font-size:15px;line-height:1.55;color:#374151;\">This is a test message from your {{appName}} panel. If you received this, outbound SMTP is working with the branded mail template.</p>\n<table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" style=\"border:1px solid #d7dde5;\">\n  <tr>\n    <td style=\"padding:10px 12px;border-bottom:1px solid #d7dde5;font-size:12px;color:#6b7280;width:88px;\">Sent</td>\n    <td style=\"padding:10px 12px;border-bottom:1px solid #d7dde5;font-size:13px;color:#111827;\">{{sentAt}}</td>\n  </tr>\n  <tr>\n    <td style=\"padding:10px 12px;font-size:12px;color:#6b7280;\">SMTP</td>\n    <td style=\"padding:10px 12px;font-size:13px;color:#111827;\">{{smtpHost}}:{{smtpPort}}</td>\n  </tr>\n</table>\n",
  "test-mail.subject.txt": "{{appName}} test mail\n",
  "test-mail.txt": "Hello,\n\nThis is a test message from your {{appName}} panel.\nIf you received this, outbound SMTP is working with the branded mail template.\n\nSent at {{sentAt}}\nSMTP: {{smtpHost}}:{{smtpPort}}\n",
  "verify-email.html": "<p style=\"margin:0 0 14px;font-size:16px;line-height:1.45;color:#111827;\">Hi {{username}},</p>\n<p style=\"margin:0 0 18px;font-size:15px;line-height:1.55;color:#374151;\">Confirm your email to finish setting up your {{appName}} account.</p>\n<p style=\"margin:0 0 18px;\">\n  <a href=\"{{actionUrl}}\" style=\"display:inline-block;background:#2563eb;color:#ffffff;text-decoration:none;font-weight:600;font-size:14px;padding:11px 18px;border:1px solid #1d4ed8;\">Verify email</a>\n</p>\n<p style=\"margin:0 0 6px;font-size:12px;line-height:1.45;color:#6b7280;\">Or open this link:</p>\n<p style=\"margin:0 0 14px;font-size:13px;line-height:1.45;word-break:break-all;\"><a href=\"{{actionUrl}}\" style=\"color:#2563eb;\">{{actionUrl}}</a></p>\n<p style=\"margin:0;padding-top:12px;border-top:1px solid #d7dde5;font-size:12px;color:#6b7280;\">This link expires in {{expiresIn}}.</p>\n",
  "verify-email.subject.txt": "Verify your {{appName}} email\n",
  "verify-email.txt": "Hi {{username}},\n\nConfirm your email to finish setting up your {{appName}} account:\n\n{{actionUrl}}\n\nThis link expires in {{expiresIn}}.\n",
};
