-- AlterTable
ALTER TABLE `Node` ADD COLUMN `uuid` VARCHAR(191) NULL;
ALTER TABLE `Node` ADD COLUMN `tags` JSON NOT NULL DEFAULT ('[]');
ALTER TABLE `Node` ADD COLUMN `memoryOverallocate` INTEGER NOT NULL DEFAULT 0;
ALTER TABLE `Node` ADD COLUMN `diskMb` INTEGER NOT NULL DEFAULT 0;
ALTER TABLE `Node` ADD COLUMN `diskOverallocate` INTEGER NOT NULL DEFAULT 0;
ALTER TABLE `Node` ADD COLUMN `cpuLimit` INTEGER NOT NULL DEFAULT 0;
ALTER TABLE `Node` ADD COLUMN `cpuOverallocate` INTEGER NOT NULL DEFAULT 0;
ALTER TABLE `Node` ADD COLUMN `uploadLimitMb` INTEGER NOT NULL DEFAULT 256;
ALTER TABLE `Node` ADD COLUMN `daemonBaseDirectory` VARCHAR(191) NOT NULL DEFAULT '/var/lib/guartrix';
ALTER TABLE `Node` ADD COLUMN `sftpAlias` VARCHAR(191) NULL;
ALTER TABLE `Node` ADD COLUMN `deployable` BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE `Node` ADD COLUMN `maintenanceMode` BOOLEAN NOT NULL DEFAULT false;

-- Backfill UUIDs for existing rows
UPDATE `Node` SET `uuid` = UUID() WHERE `uuid` IS NULL;

-- Make uuid required + unique
ALTER TABLE `Node` MODIFY `uuid` VARCHAR(191) NOT NULL;
CREATE UNIQUE INDEX `Node_uuid_key` ON `Node`(`uuid`);
