import type { FileManagerActionsProps } from "./types";
import { useFileBrowserState } from "./useFileBrowserState";
import { useFileDialogs } from "./useFileDialogs";
import { useFileEditorState } from "./useFileEditorState";
import { useFileMutations } from "./useFileMutations";

export type { Dialog, FileManagerActionsProps } from "./types";

export function useFileManagerActions({
  serverId,
  onError,
  diskMb,
  active = true,
  canReadContent = true,
  canUpdate = true,
  canCreate = true,
  canUpload = true,
  canDelete = true,
  canDownload = true,
  canArchive = true,
}: FileManagerActionsProps) {
  const dialogs = useFileDialogs();
  const browser = useFileBrowserState({ serverId, onError, active });
  const editor = useFileEditorState({
    serverId,
    onError,
    t: browser.t,
    canUpdate,
    askDiscard: dialogs.askDiscard,
    setBusy: browser.setBusy,
  });
  const mutations = useFileMutations({
    serverId,
    onError,
    t: browser.t,
    canReadContent,
    canUpdate,
    canCreate,
    canUpload,
    canDelete,
    canDownload,
    canArchive,
    cwd: browser.cwd,
    someSelected: browser.someSelected,
    selected: browser.selected,
    newFolder: browser.newFolder,
    setNewFolder: browser.setNewFolder,
    setBusy: browser.setBusy,
    load: browser.load,
    bumpTree: browser.bumpTree,
    setUploadProgress: browser.setUploadProgress,
    fileInputRef: browser.fileInputRef,
    setDialog: dialogs.setDialog,
    setTabs: editor.setTabs,
    activePath: editor.activePath,
    setActivePath: editor.setActivePath,
    setPaneMode: editor.setPaneMode,
    setMobileTreeOpen: browser.setMobileTreeOpen,
    openFileAtPath: editor.openFileAtPath,
  });

  return {
    t: browser.t,
    serverId,
    diskMb,
    canUpdate,
    canCreate,
    canUpload,
    canDelete,
    canDownload,
    canArchive,
    cwd: browser.cwd,
    entries: browser.entries,
    loading: browser.loading,
    busy: browser.busy,
    tabs: editor.tabs,
    activePath: editor.activePath,
    setActivePath: editor.setActivePath,
    setPaneMode: editor.setPaneMode,
    newFolder: browser.newFolder,
    setNewFolder: browser.setNewFolder,
    selected: browser.selected,
    filter: browser.filter,
    setFilter: browser.setFilter,
    uploadProgress: browser.uploadProgress,
    dragActive: browser.dragActive,
    setDragActive: browser.setDragActive,
    treeWidth: browser.treeWidth,
    treeCollapsed: browser.treeCollapsed,
    mobileTreeOpen: browser.mobileTreeOpen,
    setMobileTreeOpen: browser.setMobileTreeOpen,
    treeRefreshKey: browser.treeRefreshKey,
    contextMenu: browser.contextMenu,
    setContextMenu: browser.setContextMenu,
    disk: browser.disk,
    dialog: dialogs.dialog,
    setDialog: dialogs.setDialog,
    dialogBusy: dialogs.dialogBusy,
    fileInputRef: browser.fileInputRef,
    activeTab: editor.activeTab,
    anyDirty: editor.anyDirty,
    crumbs: browser.crumbs,
    allSelected: browser.allSelected,
    someSelected: browser.someSelected,
    showEditor: editor.showEditor,
    treeVisibleDesktop: browser.treeVisibleDesktop,
    treeVisibleMobile: browser.treeVisibleMobile,
    askDiscard: dialogs.askDiscard,
    runDialogAction: dialogs.runDialogAction,
    load: browser.load,
    bumpTree: browser.bumpTree,
    toggleSelect: browser.toggleSelect,
    toggleSelectAll: browser.toggleSelectAll,
    toggleTree: browser.toggleTree,
    updateActiveContent: editor.updateActiveContent,
    saveFile: editor.saveFile,
    closeTab: editor.closeTab,
    onResizeStart: browser.onResizeStart,
    ...mutations,
  };
}
