#!/usr/bin/env bash
# Guartrix remote daemon installer (node).
# Run on the game node / VPS that should host Minecraft containers.
#
# Recommended (download, then run):
#   curl -Lo /tmp/guartrix-daemon.sh https://YOUR_PANEL/install-daemon.sh
#   sudo bash /tmp/guartrix-daemon.sh \
#     --token TOKEN --node-id NODE_ID --panel https://panel.example.com --fqdn NODE_IP --port 8081 \
#     --repo https://github.com/TomThermo/guartrix.git
#
# Or from a local checkout:
#   sudo bash scripts/install-daemon.sh --token TOKEN --node-id NODE_ID --fqdn 1.2.3.4 --port 8081

set -euo pipefail

TOKEN=""
NODE_ID=""
PANEL_URL=""
FQDN=""
DAEMON_PORT="8081"
INSTALL_DIR="/opt/guartrix"
DATA_DIR="/var/lib/guartrix"
REPO_URL="${GUARTRIX_REPO_URL:-https://github.com/TomThermo/guartrix.git}"
BRANCH="${GUARTRIX_BRANCH:-main}"
SFTP_PORT="${SFTP_PORT:-2022}"

usage() {
  cat <<'EOF'
Guartrix daemon installer

Required:
  --token TOKEN          Daemon shared secret from the panel (System → Add node)
  --node-id ID           Panel node id (JWT claims)

Optional:
  --panel URL            Panel base URL (PANEL_URL for SFTP auth callbacks)
  --fqdn HOST            Public IP or hostname of this node
  --port PORT            Daemon listen port (default: 8081)
  --sftp-port PORT       SFTP listen port (default: 2022)
  --dir PATH             Install directory (default: /opt/guartrix)
  --data PATH            Server data directory (default: /var/lib/guartrix)
  --repo URL             Git clone URL (default: TomThermo/guartrix)
  --branch NAME          Git branch (default: main)
  -h, --help             Show help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --token) TOKEN="${2:-}"; shift 2 ;;
    --node-id) NODE_ID="${2:-}"; shift 2 ;;
    --panel) PANEL_URL="${2:-}"; shift 2 ;;
    --fqdn) FQDN="${2:-}"; shift 2 ;;
    --port) DAEMON_PORT="${2:-}"; shift 2 ;;
    --sftp-port) SFTP_PORT="${2:-}"; shift 2 ;;
    --dir) INSTALL_DIR="${2:-}"; shift 2 ;;
    --data) DATA_DIR="${2:-}"; shift 2 ;;
    --repo) REPO_URL="${2:-}"; shift 2 ;;
    --branch) BRANCH="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage; exit 1 ;;
  esac
done

if [[ -z "$TOKEN" ]]; then
  echo "ERROR: --token is required (create a node in the panel first)." >&2
  exit 1
fi
if [[ -z "$NODE_ID" ]]; then
  echo "ERROR: --node-id is required (panel node id for JWT auth)." >&2
  exit 1
fi

if [[ "$(id -u)" -ne 0 ]]; then
  echo "ERROR: run as root (sudo)." >&2
  exit 1
fi

export DEBIAN_FRONTEND=noninteractive
echo "[guartrix] Installing remote daemon (node)…"

apt-get update -y >/dev/null
apt-get install -y ca-certificates curl gnupg git openssl tar ufw >/dev/null

if ! command -v docker >/dev/null 2>&1; then
  echo "[guartrix] Installing Docker…"
  curl -fsSL https://get.docker.com | sh
  systemctl enable --now docker
fi

if ! command -v node >/dev/null 2>&1 || [[ "$(node -v 2>/dev/null | sed 's/^v//' | cut -d. -f1)" -lt 22 ]]; then
  echo "[guartrix] Installing Node.js 22…"
  curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
  apt-get install -y nodejs
fi

# Prefer an existing monorepo checkout, else clone.
ROOT=""
if [[ -f "$(pwd)/apps/daemon/package.json" ]]; then
  ROOT="$(pwd)"
elif [[ -f "/home/ubuntu/Documents/Minecraft/apps/daemon/package.json" ]]; then
  ROOT="/home/ubuntu/Documents/Minecraft"
elif [[ -f "${INSTALL_DIR}/apps/daemon/package.json" ]]; then
  ROOT="$INSTALL_DIR"
  git -C "$ROOT" fetch --depth 1 origin "$BRANCH" 2>/dev/null || true
  git -C "$ROOT" checkout "$BRANCH" 2>/dev/null || true
  git -C "$ROOT" pull --ff-only origin "$BRANCH" 2>/dev/null || true
elif [[ -n "$REPO_URL" ]]; then
  mkdir -p "$(dirname "$INSTALL_DIR")"
  rm -rf "$INSTALL_DIR"
  git clone --depth 1 --branch "$BRANCH" "$REPO_URL" "$INSTALL_DIR"
  ROOT="$INSTALL_DIR"
else
  echo "ERROR: no Guartrix source found and no --repo given." >&2
  exit 1
fi

mkdir -p "$DATA_DIR/servers" "$DATA_DIR/run" "$DATA_DIR/backups"
chmod 700 "$DATA_DIR"

ENV_FILE="$DATA_DIR/daemon.env"
MYSQL_PASS="$(openssl rand -hex 24)"
cat > "$ENV_FILE" <<EOF
# Generated by scripts/install-daemon.sh — do not commit
DAEMON_TOKEN=${TOKEN}
DAEMON_NODE_ID=${NODE_ID}
DAEMON_PORT=${DAEMON_PORT}
DAEMON_HOST=0.0.0.0
DATA_DIR=${DATA_DIR}
PUBLIC_HOST=${FQDN:-0.0.0.0}
PANEL_URL=${PANEL_URL:-}
SFTP_PORT=${SFTP_PORT}
SFTP_ENABLED=true
DAEMON_JWT_TTL=900
DAEMON_JWT_WS_TTL=3600
DAEMON_JWT_LEGACY=false
DOCKER_IMAGE=eclipse-temurin:25-jre-jammy
MYSQL_ROOT_PASSWORD=${MYSQL_PASS}
MYSQL_PORT=3306
MYSQL_IMAGE=mysql:8.4
MANAGE_FIREWALL=true
GUARTRIX_ROOT=${ROOT}
EOF
chmod 600 "$ENV_FILE"

echo "[guartrix] Building daemon from ${ROOT}…"
cd "$ROOT"
npm install
if [[ -f apps/daemon/src/index.ts ]]; then
  npm run build -w @msm/shared
  npm run build -w @msm/node-agent
  npm run build -w @msm/daemon
elif [[ -f apps/daemon/dist/index.js ]]; then
  echo "[guartrix] Using prebuilt release daemon (no TypeScript sources)"
else
  echo "[guartrix] ERROR: neither apps/daemon/src nor apps/daemon/dist/index.js found" >&2
  exit 1
fi

UNIT=/etc/systemd/system/guartrix-daemon.service
cat > "$UNIT" <<EOF
[Unit]
Description=Guartrix node daemon (multi-node)
After=network-online.target docker.service
Wants=network-online.target
Requires=docker.service

[Service]
Type=simple
WorkingDirectory=${ROOT}
EnvironmentFile=${ENV_FILE}
Environment=NODE_ENV=production
Environment=GUARTRIX_ROOT=${ROOT}
ExecStart=$(command -v node) ${ROOT}/apps/daemon/dist/index.js
Restart=always
RestartSec=3
KillMode=process
TimeoutStopSec=20

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now guartrix-daemon.service

if command -v ufw >/dev/null 2>&1; then
  ufw allow "${DAEMON_PORT}/tcp" >/dev/null 2>&1 || true
  ufw allow "${SFTP_PORT}/tcp" >/dev/null 2>&1 || true
  ufw allow 25565:25600/tcp >/dev/null 2>&1 || true
fi

sleep 1
if systemctl is-active --quiet guartrix-daemon.service; then
  echo "[guartrix] Daemon is running on 0.0.0.0:${DAEMON_PORT}"
else
  echo "[guartrix] WARN: service not active — check: journalctl -u guartrix-daemon -e" >&2
fi

echo
echo "Next steps in the panel (System):"
echo "  1. Node host/FQDN must reach this machine on port ${DAEMON_PORT}"
echo "  2. Click “Test connection”"
if [[ -n "$PANEL_URL" ]]; then
  echo "  3. Panel: ${PANEL_URL}"
fi
echo "  4. Firewall: ${DAEMON_PORT}/tcp + ${SFTP_PORT}/tcp + game ports"
echo
echo "Token is stored in ${ENV_FILE}"
