#!/usr/bin/env node
/**
 * Start production: daemon (:DAEMON_PORT) + API (:API_PORT) + web (:WEB_PORT / HTTPS).
 * Assumes `npm run build` already ran (use `npm run prod` to build + start).
 */
import { spawn } from "node:child_process";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..");

function loadEnvFile(filePath) {
  try {
    const raw = fs.readFileSync(filePath, "utf8");
    for (const line of raw.split(/\r?\n/)) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const eq = trimmed.indexOf("=");
      if (eq <= 0) continue;
      const key = trimmed.slice(0, eq).trim();
      let val = trimmed.slice(eq + 1).trim();
      if (
        (val.startsWith('"') && val.endsWith('"')) ||
        (val.startsWith("'") && val.endsWith("'"))
      ) {
        val = val.slice(1, -1);
      }
      if (process.env[key] === undefined) process.env[key] = val;
    }
  } catch {
    // optional
  }
}

function ensureDaemonEnv() {
  const dataDir = path.resolve(rootDir, process.env.DATA_DIR ?? "./data");
  fs.mkdirSync(dataDir, { recursive: true });
  const envPath = path.join(dataDir, "daemon.env");
  loadEnvFile(envPath);

  let token = process.env.DAEMON_TOKEN?.trim();
  if (!token) {
    token = crypto.randomBytes(32).toString("hex");
    process.env.DAEMON_TOKEN = token;
  }
  const port = process.env.DAEMON_PORT ?? "8081";
  const host = process.env.DAEMON_HOST ?? "127.0.0.1";

  // Preserve existing MySQL root password across regenerations
  let mysqlPassword = process.env.MYSQL_ROOT_PASSWORD?.trim();
  if (!mysqlPassword) {
    try {
      const raw = fs.readFileSync(envPath, "utf8");
      const m = raw.match(/^MYSQL_ROOT_PASSWORD=(.*)$/m);
      mysqlPassword = m?.[1]?.trim() || "";
    } catch {
      // none
    }
  }
  if (!mysqlPassword) {
    mysqlPassword = crypto.randomBytes(24).toString("hex");
  }
  process.env.MYSQL_ROOT_PASSWORD = mysqlPassword;
  const mysqlPort = process.env.MYSQL_PORT ?? "3306";
  process.env.MYSQL_PORT = mysqlPort;

  const body = [
    `# Generated by Guartrix start-prod — do not commit`,
    `DAEMON_TOKEN=${token}`,
    `DAEMON_PORT=${port}`,
    `DAEMON_HOST=${host}`,
    `DATA_DIR=${dataDir}`,
    `PUBLIC_HOST=${process.env.PUBLIC_HOST ?? "127.0.0.1"}`,
    `DOCKER_IMAGE=${process.env.DOCKER_IMAGE ?? "eclipse-temurin:25-jre-jammy"}`,
    `MYSQL_ROOT_PASSWORD=${mysqlPassword}`,
    `MYSQL_PORT=${mysqlPort}`,
    `MYSQL_IMAGE=${process.env.MYSQL_IMAGE ?? "mysql:8.4"}`,
    "",
  ].join("\n");
  fs.writeFileSync(envPath, body, { mode: 0o600 });
  process.env.DAEMON_TOKEN = token;
  process.env.DAEMON_PORT = String(port);
  process.env.DAEMON_HOST = host;
  return { envPath, port, host };
}

loadEnvFile(path.join(rootDir, ".env"));
const daemonInfo = ensureDaemonEnv();
loadEnvFile(path.join(rootDir, "data/daemon.env"));

// Prefer IPv4 for outbound HTTPS — broken IPv6 makes Modrinth (undici) hang.
const dnsOrderFlag = "--dns-result-order=ipv4first";
const existingNodeOpts = process.env.NODE_OPTIONS?.trim() ?? "";
if (!existingNodeOpts.includes("dns-result-order")) {
  process.env.NODE_OPTIONS = existingNodeOpts
    ? `${existingNodeOpts} ${dnsOrderFlag}`
    : dnsOrderFlag;
}

const children = [];

function start(name, command, args) {
  const child = spawn(command, args, {
    cwd: rootDir,
    stdio: "inherit",
    env: process.env,
  });
  child.on("exit", (code, signal) => {
    console.log(
      `[guartrix] ${name} exited (code=${code ?? "null"} signal=${signal ?? "null"})`,
    );
    shutdown(code ?? 1);
  });
  children.push(child);
  return child;
}

let shuttingDown = false;
function shutdown(code = 0) {
  if (shuttingDown) return;
  shuttingDown = true;
  for (const child of children) {
    try {
      child.kill("SIGTERM");
    } catch {
      // ignore
    }
  }
  setTimeout(() => process.exit(code), 500).unref?.();
}

process.on("SIGINT", () => shutdown(0));
process.on("SIGTERM", () => shutdown(0));

const distIndex = path.join(rootDir, "apps/web/dist/index.html");
if (!fs.existsSync(distIndex)) {
  console.error("[guartrix] No web build found. Run: npm run build");
  process.exit(1);
}

const apiDist = path.join(rootDir, "apps/api/dist/index.js");
if (!fs.existsSync(apiDist)) {
  console.error("[guartrix] No API build found. Run: npm run build");
  process.exit(1);
}

const daemonDist = path.join(rootDir, "apps/daemon/dist/index.js");
if (!fs.existsSync(daemonDist)) {
  console.error("[guartrix] No daemon build found. Run: npm run build");
  process.exit(1);
}

console.log(
  `[guartrix] Starting production — daemon :${daemonInfo.port}, API :${process.env.API_PORT ?? 3001}, web :${process.env.WEB_PORT ?? 80}, https :${process.env.HTTPS_PORT ?? 443}`,
);

start("daemon", "npm", ["run", "start", "-w", "@msm/daemon"]);
start("api", "npm", ["run", "start", "-w", "@msm/api"]);

const webPort = Number(process.env.WEB_PORT ?? 80);
const httpsPort = Number(process.env.HTTPS_PORT ?? 443);
const needsRoot =
  (Number.isFinite(webPort) && webPort > 0 && webPort < 1024) ||
  (Number.isFinite(httpsPort) && httpsPort > 0 && httpsPort < 1024);
const webScript = path.join(rootDir, "scripts/prod-web.mjs");
if (needsRoot) {
  console.log(
    `[guartrix] Privileged web ports require root — starting web with sudo`,
  );
  start("web", "sudo", [
    "-n",
    "env",
    `WEB_PORT=${webPort}`,
    `HTTPS_PORT=${httpsPort}`,
    `HTTPS_ENABLED=${process.env.HTTPS_ENABLED ?? "true"}`,
    `WEB_HOST=${process.env.WEB_HOST ?? "0.0.0.0"}`,
    `API_PORT=${process.env.API_PORT ?? 3001}`,
    `API_PROXY_HOST=${process.env.API_PROXY_HOST ?? "127.0.0.1"}`,
    `PUBLIC_HOST=${process.env.PUBLIC_HOST ?? "localhost"}`,
    `MANAGE_FIREWALL=${process.env.MANAGE_FIREWALL ?? "true"}`,
    `HOME=${process.env.HOME ?? "/home/ubuntu"}`,
    "node",
    webScript,
  ]);
} else {
  start("web", "node", [webScript]);
}
