import { randomBytes } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { nanoid } from "nanoid";
import { config } from "../config.js";
import { prisma } from "../db.js";
import { hostPublicIp } from "./host-resources.js";
import { syncNodeSftpDns } from "./nodes-dns.js";
import {
  resolveCreatePlacement,
  type CreatePlacementInput,
} from "./nodes-placement.js";
import { generateDaemonToken, hashDaemonToken } from "./nodes-token.js";

const DAEMON_ENV_FILE = "daemon.env";
const DEFAULT_SFTP_PORT = 2022;

export async function resolveCreateNodeId(
  requestedId?: string | null,
  opts?: Pick<
    CreatePlacementInput,
    "memoryMb" | "diskMb" | "cpuLimit" | "requestedStorageId"
  >,
): Promise<string> {
  const { nodeId } = await resolveCreatePlacement({
    requestedNodeId: requestedId ?? undefined,
    requestedStorageId: opts?.requestedStorageId,
    memoryMb: opts?.memoryMb ?? 512,
    diskMb: opts?.diskMb,
    cpuLimit: opts?.cpuLimit,
  });
  return nodeId;
}

function readDaemonEnvValue(file: string, key: string): string | null {
  try {
    const raw = fs.readFileSync(file, "utf8");
    const match = raw.match(new RegExp(`^${key}=(.*)$`, "m"));
    const val = match?.[1]?.trim();
    return val || null;
  } catch {
    return null;
  }
}

function writeLocalDaemonEnv(token: string, port: number, nodeId: string): void {
  const file = path.join(config.dataDir, DAEMON_ENV_FILE);
  const mysqlPassword =
    process.env.MYSQL_ROOT_PASSWORD?.trim() ||
    readDaemonEnvValue(file, "MYSQL_ROOT_PASSWORD") ||
    randomBytes(24).toString("hex");
  process.env.MYSQL_ROOT_PASSWORD = mysqlPassword;
  const mysqlPort =
    process.env.MYSQL_PORT?.trim() || readDaemonEnvValue(file, "MYSQL_PORT") || "3306";
  process.env.MYSQL_PORT = mysqlPort;
  const publicIp =
    process.env.PUBLIC_IP?.trim() || readDaemonEnvValue(file, "PUBLIC_IP") || hostPublicIp() || "";
  const sftpPort =
    process.env.SFTP_PORT?.trim() ||
    readDaemonEnvValue(file, "SFTP_PORT") ||
    String(DEFAULT_SFTP_PORT);
  const panelUrl =
    process.env.PANEL_URL?.trim() || `http://127.0.0.1:${process.env.API_PORT ?? 3001}`;
  // Bind port for the local process. When DAEMON_PUBLIC_HOST is set, node.daemonPort
  // is the public HTTPS port (443) and must not be written as the loopback listen port
  // (prod-web already owns :443). Prefer DAEMON_PROXY_PORT / 8081 in that case.
  const bindPort = process.env.DAEMON_PUBLIC_HOST?.trim()
    ? Number(process.env.DAEMON_PROXY_PORT || process.env.DAEMON_BIND_PORT || 8081) || 8081
    : Number(process.env.DAEMON_PORT ?? port) || port || 8081;
  const body = [
    `# Generated by Guartrix panel — do not commit`,
    `DAEMON_TOKEN=${token}`,
    `DAEMON_NODE_ID=${nodeId}`,
    `DAEMON_PORT=${bindPort}`,
    `DAEMON_HOST=127.0.0.1`,
    `DATA_DIR=${config.dataDir}`,
    `PUBLIC_HOST=${config.publicHost}`,
    ...(publicIp ? [`PUBLIC_IP=${publicIp}`] : []),
    `PANEL_URL=${panelUrl}`,
    `SFTP_PORT=${sftpPort}`,
    `SFTP_ENABLED=true`,
    `DOCKER_IMAGE=${config.dockerImage}`,
    `DOCKER_NETWORK_MODE=${(process.env.DOCKER_NETWORK_MODE ?? "per_server").trim() || "per_server"}`,
    `MYSQL_ROOT_PASSWORD=${mysqlPassword}`,
    `MYSQL_PORT=${mysqlPort}`,
    `MYSQL_IMAGE=${process.env.MYSQL_IMAGE ?? "mysql:8.4"}`,
    `# Short-lived HS256 JWTs signed with DAEMON_TOKEN. Set DAEMON_JWT_LEGACY=true only for old daemons.`,
    `DAEMON_JWT_TTL=${process.env.DAEMON_JWT_TTL?.trim() || "900"}`,
    `DAEMON_JWT_WS_TTL=${process.env.DAEMON_JWT_WS_TTL?.trim() || "3600"}`,
    `DAEMON_JWT_LEGACY=${process.env.DAEMON_JWT_LEGACY?.trim() || "false"}`,
    "",
  ].join("\n");
  fs.mkdirSync(config.dataDir, { recursive: true });
  fs.writeFileSync(file, body, { mode: 0o600 });
}

export function writeLocalDaemonEnvIfLocal(token: string, port: number, nodeId?: string): void {
  if (!nodeId) {
    // Best-effort: keep previous NODE_ID from env file if caller omitted it
    const existing =
      readDaemonEnvValue(path.join(config.dataDir, DAEMON_ENV_FILE), "DAEMON_NODE_ID") || "";
    writeLocalDaemonEnv(token, port, existing || "unknown");
    return;
  }
  writeLocalDaemonEnv(token, port, nodeId);
}

/** Ensure a local node exists; write data/daemon.env for the local daemon process. */
export async function ensureLocalNode(): Promise<{
  nodeId: string;
  token: string;
}> {
  const existing = await prisma.node.findFirst({ where: { isLocal: true } });
  const port = Number(process.env.DAEMON_PORT ?? 8081);
  const fqdn = process.env.DAEMON_FQDN ?? "127.0.0.1";

  if (existing) {
    // Prefer token from env / daemon.env so restarts stay in sync
    let token = process.env.DAEMON_TOKEN?.trim() || readTokenFromDaemonEnv() || "";
    if (!token) {
      token = generateDaemonToken();
      await prisma.node.update({
        where: { id: existing.id },
        data: { tokenHash: hashDaemonToken(token) },
      });
      writeLocalDaemonEnv(token, port, existing.id);
    } else if (hashDaemonToken(token) !== existing.tokenHash) {
      await prisma.node.update({
        where: { id: existing.id },
        data: { tokenHash: hashDaemonToken(token) },
      });
      writeLocalDaemonEnv(token, port, existing.id);
    } else {
      writeLocalDaemonEnv(token, port, existing.id);
    }

    // Assign servers missing a node
    const assigned = await prisma.server.updateMany({
      where: { nodeId: null },
      data: { nodeId: existing.id },
    });
    if (assigned.count > 0) {
      console.info(
        `[guartrix] Migrated ${assigned.count} server(s) onto local node ${existing.name}`,
      );
    }

    await syncNodeSftpDns(existing.id);
    return { nodeId: existing.id, token };
  }

  const token = process.env.DAEMON_TOKEN?.trim() || generateDaemonToken();
  const node = await prisma.node.create({
    data: {
      id: nanoid(12),
      name: "Local",
      fqdn,
      scheme: "http",
      daemonPort: port,
      tokenHash: hashDaemonToken(token),
      isLocal: true,
      status: "UNKNOWN",
      sftpPort: Number(process.env.SFTP_PORT ?? DEFAULT_SFTP_PORT) || DEFAULT_SFTP_PORT,
    },
  });

  writeLocalDaemonEnv(token, port, node.id);

  const migrated = await prisma.server.updateMany({
    where: { nodeId: null },
    data: { nodeId: node.id },
  });
  console.info(
    `[guartrix] Created local node "${node.name}" and assigned ${migrated.count} server(s)`,
  );

  await syncNodeSftpDns(node.id);
  return { nodeId: node.id, token };
}

function readTokenFromDaemonEnv(): string | null {
  try {
    const raw = fs.readFileSync(path.join(config.dataDir, DAEMON_ENV_FILE), "utf8");
    for (const line of raw.split(/\r?\n/)) {
      const m = /^DAEMON_TOKEN=(.*)$/.exec(line.trim());
      if (m) return m[1]!.trim();
    }
  } catch {
    // ignore
  }
  return null;
}

export function getLocalDaemonToken(): string {
  return process.env.DAEMON_TOKEN?.trim() || readTokenFromDaemonEnv() || "";
}

export async function getNodeForServer(serverId: string) {
  const server = await prisma.server.findUnique({
    where: { id: serverId },
    include: { node: true },
  });
  if (!server) return null;
  if (server.node) return server.node;
  const local = await prisma.node.findFirst({ where: { isLocal: true } });
  if (local) {
    await prisma.server.update({
      where: { id: serverId },
      data: { nodeId: local.id },
    });
    return local;
  }
  return null;
}
